name: Pull Request Tests
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.23.4
      - run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
      - run: |
          CGO_LDFLAGS="$(mecab-config --libs)" CGO_CFLAGS="$(mecab-config --cflags)" go test -v ./...

  macos-test:
    runs-on: macos-latest 

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.23.4
      - run: |
          brew install mecab mecab-ipadic
      - run: |
          CGO_LDFLAGS="$(mecab-config --libs)" CGO_CFLAGS="$(mecab-config --cflags)" go test -v ./...

  windows-test:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.23.4
      - uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
        with:
          dotnet-version: 8
      - uses: msys2/setup-msys2@d44ca8e88d8b43d56cf5670f91747359d5537f97 # v2.26.0
        with:
          install: autoconf bison make automake1.16 automake-wrapper mingw-w64-x86_64-gcc mingw-w64-x86_64-libtool mingw-w64-x86_64-libiconv
      - run: |
          dotnet tool install -g MecabConfig
      - shell: msys2 {0}
        run: |
          ./assets/bin/install-mecab-mingw-on-github-actions
      - run: |
          go env
          go test -v ./...
